application: amit-wiki
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  
- url: (/?(?:[a-zA-Z0-9_-]+/?)*)
  script: src.main.app

- url: /static
  static_dir: src/static
  

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
  